version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: project_db_name
    volumes:
      - postgres_data:/data/postgres
    networks:
      - app-net

  redis:
    image: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    networks:
      - app-net

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - database
      - redis
    networks:
      - app-net


networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
